"""Employer enrichment and the outbound queue.

The stakes are one-directional here. A missed contact costs one outreach email. A
*wrong* contact sends a tailored CV, a cover letter and a personal phone number to
a stranger, and cannot be recalled. Every test below is about the second kind.
"""

from pathlib import Path

import pytest

from src.contracts import Employer, EmployerContact
from src.enrich import (
    dedupe_contacts,
    guess_role_addresses,
    is_hiring_address,
    name_tokens,
    plausible_domain,
    score_harvested,
)
from src.generate import split_email
from src.outbound import build_item, render_eml, unresolved_fields


# --- address filtering -------------------------------------------------------


@pytest.mark.parametrize("email", [
    "careers@acme.com", "jobs@acme.com", "hello@acme.com", "talent@acme.com",
])
def test_plausible_hiring_addresses_are_kept(email):
    assert is_hiring_address(email, "acme.com")


@pytest.mark.parametrize("email,why", [
    ("noreply@acme.com", "automated sender"),
    ("postmaster@acme.com", "mail infrastructure"),
    ("privacy@acme.com", "not hiring"),
    ("sales@acme.com", "wrong department"),
    # Vulnerability-disclosure inboxes are real, reliable, and completely wrong:
    # harvesting security.txt made responsibledisclosure@adyen.com Adyen's "best
    # careers contact".
    ("responsibledisclosure@acme.com", "security disclosure"),
    ("security@acme.com", "security disclosure"),
    ("bugbounty@acme.com", "security disclosure"),
    # A vendor address that appears on thousands of sites.
    ("someone@sentry.io", "third-party vendor"),
    # Somebody else's domain entirely.
    ("careers@unrelated.com", "different company"),
])
def test_non_hiring_addresses_are_rejected(email, why):
    assert not is_hiring_address(email, "acme.com"), why


def test_subdomain_addresses_are_accepted():
    assert is_hiring_address("careers@jobs.acme.com", "acme.com")


def test_malformed_addresses_are_rejected():
    for bad in ("", "not-an-email", "a@b@c.com", "careers@logo.png"):
        assert not is_hiring_address(bad, "acme.com")


# --- confidence --------------------------------------------------------------


def test_role_addresses_outrank_generic_inboxes():
    assert score_harvested("careers@acme.com") > score_harvested("hello@acme.com")
    assert score_harvested("hello@acme.com") > score_harvested("bob@acme.com")


def test_guessed_addresses_are_labelled_as_guesses():
    guesses = guess_role_addresses("acme.com")
    assert guesses, "should produce RFC 2142 candidates"
    assert all(g.source == "rfc2142_guess" for g in guesses)
    assert all(g.confidence < 0.5 for g in guesses), (
        "a convention must never score as high as an observed address"
    )


def test_observed_address_beats_the_same_address_guessed():
    """`careers@acme.com` may be both found on the careers page and generated by
    convention. Reporting the guess would understate what is actually known."""
    merged = dedupe_contacts([
        EmployerContact(email="careers@acme.com", source="rfc2142_guess",
                        confidence=0.45),
        EmployerContact(email="careers@acme.com", source="mailto", confidence=0.95,
                        evidence="https://acme.com/careers"),
    ])
    assert len(merged) == 1
    assert merged[0].source == "mailto"
    assert merged[0].confidence == 0.95


# --- domain inference --------------------------------------------------------


def test_plausible_domain_is_only_a_starting_guess():
    assert plausible_domain("Branch International") == "branchinternational.com"
    assert plausible_domain("") == ""


def test_name_tokens_drop_uninformative_words():
    """"Global", "Technologies" and "Ltd" match almost any homepage, so they
    cannot be used as evidence that a domain belongs to a company."""
    assert name_tokens("Copia Global") == ["copia"]
    assert name_tokens("Acme Technologies Ltd") == ["acme"]
    # If every token is generic, fall back rather than returning nothing.
    assert name_tokens("Global Technologies") != []


# --- outbound: what must never be sent ---------------------------------------


def item(tmp_path: Path, employer=None, body="Hi there.", answers="", **kw):
    return build_item(
        slug="acme-engineer", company="Acme", role="Senior Engineer",
        apply_url="https://acme.com/jobs/1", subject="Senior Engineer at Acme",
        body=body, employer=employer, package_dir=tmp_path, answers_text=answers,
        **kw,
    )


def employer_with(**kw) -> Employer:
    contact = EmployerContact(**kw)
    return Employer(name="Acme", slug="acme", domain="acme.com", contacts=[contact])


def test_no_contact_is_held_for_review(tmp_path):
    result = item(tmp_path, employer=None)
    assert result.status == "needs_review"
    assert "no_contact" in result.blockers


def test_guessed_contact_is_held_for_review(tmp_path):
    """The escalation rule from CLAUDE.md: the pipeline does not guess and send."""
    result = item(tmp_path, employer=employer_with(
        email="careers@acme.com", source="rfc2142_guess", confidence=0.45,
    ))
    assert result.status == "needs_review"
    assert "guessed_contact" in result.blockers


def test_observed_contact_is_ready_to_send(tmp_path):
    result = item(tmp_path, employer=employer_with(
        email="careers@acme.com", source="mailto", confidence=0.95,
        evidence="https://acme.com/careers",
    ))
    assert result.status == "ready"
    assert result.blockers == []
    assert result.to_email == "careers@acme.com"


def test_unresolved_markers_block_sending(tmp_path):
    """`[NEEDS YOUR INPUT: ...]` is the model saying it does not know. That
    admission has to become a gate, or it becomes a lie in a sent email."""
    result = item(
        tmp_path,
        employer=employer_with(email="careers@acme.com", source="mailto",
                               confidence=0.95),
        answers="## Salary\n[NEEDS YOUR INPUT: confirm your target range]",
    )
    assert result.status == "needs_review"
    assert "unresolved_fields" in result.blockers
    assert result.unresolved == ["confirm your target range"]


def test_do_not_contact_list_is_honoured(tmp_path):
    result = item(
        tmp_path,
        employer=employer_with(email="careers@acme.com", source="mailto",
                               confidence=0.95),
        do_not_contact={"acme.com"},
    )
    assert "do_not_contact" in result.blockers
    assert result.status == "needs_review"


def test_broker_sourced_individual_is_held_for_review(tmp_path):
    """A named person from a data broker is personal data. GDPR Art. 14 gives
    them a right to know where it came from, so this never sends unreviewed."""
    result = item(tmp_path, employer=employer_with(
        email="jane@acme.com", kind="person", source="apollo", confidence=0.7,
        name="Jane Doe", title="Technical Recruiter",
    ))
    assert result.status == "needs_review"
    assert "low_confidence_person" in result.blockers


def test_empty_body_blocks_sending(tmp_path):
    result = item(tmp_path, body="   ", employer=employer_with(
        email="careers@acme.com", source="mailto", confidence=0.95,
    ))
    assert "no_email_body" in result.blockers


# --- the draft itself --------------------------------------------------------


def test_ready_draft_addresses_the_recipient(tmp_path):
    ready = item(tmp_path, employer=employer_with(
        email="careers@acme.com", source="mailto", confidence=0.95,
    ))
    raw = render_eml(ready, "Allan", "allan@example.com").decode()
    assert "To: careers@acme.com" in raw
    assert "X-JobApp-Status: ready" in raw


def test_blocked_draft_has_no_recipient(tmp_path):
    """A draft that is not ready must not open pre-addressed — one stray send
    keystroke is all it would take."""
    blocked = item(tmp_path, employer=None)
    raw = render_eml(blocked, "Allan", "allan@example.com").decode()
    assert "\nTo:" not in raw
    assert "NOT READY TO SEND" in raw
    assert "No contact address" in raw


def test_draft_lists_attachments_rather_than_attaching_them(tmp_path):
    (tmp_path / "resume.pdf").write_bytes(b"%PDF-1.4 fake")
    ready = item(tmp_path, employer=employer_with(
        email="careers@acme.com", source="mailto", confidence=0.95,
    ))
    assert any("resume.pdf" in a for a in ready.attachments)
    raw = render_eml(ready, "Allan", "allan@example.com").decode()
    assert "Attach before sending" in raw


# --- parsing the generated email ---------------------------------------------


def test_subject_is_split_from_body():
    subject, body = split_email(
        "Subject: Payments infra at Acme\n\nHi Jane,\n\nI read your post."
    )
    assert subject == "Payments infra at Acme"
    assert body.startswith("Hi Jane,")
    assert "Subject:" not in body


def test_missing_subject_still_yields_a_usable_body():
    subject, body = split_email("Hi Jane,\n\nI read your engineering post.")
    assert subject == ""
    assert body.startswith("Hi Jane,")


def test_unresolved_fields_are_deduplicated():
    found = unresolved_fields(
        "[NEEDS YOUR INPUT: notice period]",
        "[NEEDS YOUR INPUT: notice period] and [NEEDS YOUR INPUT: salary]",
    )
    assert found == ["notice period", "salary"]
